- name: Install Docker on ec2
  hosts: ec2
  become: true
  tasks:
    - name: Install Docker
      yum:
        name:
          - amazon-linux-extras
          - docker
        state: present
    - name: start docker
      systemd:
        name: docker
        state: started
    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes
